version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
    ports:
    - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mastodon-connector-svc:
    image: antonrynkovyi/mastodon-connector-svc:latest
    container_name: mastodon-connector-svc
    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    depends_on:
      - cassandra
      - kafka
    entrypoint: [ "sh", "-c", "sleep 15 && java -jar app.jar" ]

  post-gateway-svc:
    image: antonrynkovyi/post-gateway-svc:latest
    container_name: post-gateway-svc
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    depends_on:
      - mastodon-connector-svc

volumes:
  cassandra-data: